name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: SSH & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "testing"
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy React App
        run: |
          ssh ${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_APP_PATH }}
            git pull origin main
            npm install
            npm run build
            serve -s build -l 3000 &
          EOF
